# Generated by Django 5.1.7 on 2025-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='propietario',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='mueble',
            name='comision',
            field=models.IntegerField(default=10, verbose_name='Comisión de proveedor  (%)'),
        ),
    ]
