# Generated by Django 5.1.7 on 2025-04-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='fecha_final_descuento',
            new_name='fecha_fin_descuento',
        ),
    ]
