# Generated by Django 5.1.7 on 2025-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0002_rename_fecha_final_descuento_mueble_fecha_fin_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='dias',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
