# Generated by Django 4.2.6 on 2025-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0002_renta_duracion_anios_renta_duracion_meses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renta',
            old_name='duracion_anios',
            new_name='duracion_dias',
        ),
    ]
