# Generated by Django 5.1.7 on 2025-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0002_rename_propietario_mueble_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='renta',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='renta',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
