# Generated by Django 5.1.7 on 2025-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0003_alter_propietario_options_propietario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Propietario Individual'), ('empresa', 'Empresa'), ('empleado', 'Empleado de Empresa')], max_length=10),
        ),
    ]
