# Generated by Django 5.1.7 on 2025-05-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0003_renta_estado_renta_total_alter_renta_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='renta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muebles.renta'),
        ),
    ]
