# Generated by Django 5.1.7 on 2025-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0004_pedido_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='duracion_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='duracion_meses',
            field=models.IntegerField(default=0),
        ),
    ]
