# Generated by Django 5.1.7 on 2025-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0004_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='precio_diario',
            field=models.IntegerField(default=0),
        ),
    ]
