# Generated by Django 5.1.7 on 2025-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0005_alter_propietario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Propietario Individual'), ('empleado', 'Empleado de Empresa')], default='individual', max_length=10),
        ),
    ]
