# Generated by Django 5.1.7 on 2025-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0007_pedido_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='costo_domicilio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
