# Generated by Django 4.2.6 on 2025-04-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0007_alter_propietario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('CUENTA', 'Cuenta de usuario'), ('PAGOS', 'Pagos y facturación'), ('ENTREGAS', 'Entregas y logística'), ('MUEBLES', 'Productos y muebles'), ('SISTEMA', 'Sistema y mantenimiento'), ('OTROS', 'Otros')], default='CUENTA', max_length=50),
        ),
    ]
