# Generated by Django 4.2.6 on 2025-04-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0008_pregunta_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='carrito',
            name='servicio_instalacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propietario',
            name='segmento',
            field=models.CharField(choices=[('A', 'Proveedores (Fábricas, Galerías, Tiendas)'), ('B', 'Personas Naturales'), ('C', 'Personas Naturales Propietarias de Inmuebles')], default='B', max_length=1),
        ),
    ]
