# Generated by Django 5.1.7 on 2025-03-31 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0008_alter_detallepedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('importante', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Actualizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(choices=[('CUENTA', 'Cuenta de usuario'), ('PAGOS', 'Pagos y facturación'), ('ENTREGAS', 'Entregas y logística'), ('MUEBLES', 'Productos y muebles')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['orden', 'pregunta'],
            },
        ),
    ]
