# Generated by Django 5.1.7 on 2025-03-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0009_actualizacion_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='categoria',
            field=models.CharField(choices=[('CUENTA', 'Cuenta de usuario'), ('PAGOS', 'Pagos y facturación'), ('ENTREGAS', 'Entregas y logística'), ('MUEBLES', 'Productos y muebles'), ('sistema', 'sistema,mantenimiento y manejo'), ('OTROS', 'Otros')], max_length=20),
        ),
    ]
