# Generated by Django 4.2.6 on 2025-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0009_remove_propietario_tipo_carrito_servicio_instalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='segmento',
            field=models.CharField(choices=[('A', 'Proveedores (Fábricas, Galerías, Tiendas)'), ('B', 'Personas Naturales'), ('C', 'Personas Naturales (Propietarias de Inmuebles)')], default='B', max_length=1),
        ),
    ]
