# Generated by Django 5.1.7 on 2025-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0010_alter_propietario_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Propietario'), (3, 'Cliente'), (4, 'Soporte Técnico')], default=3),
        ),
    ]
