# Generated by Django 5.1.7 on 2025-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0011_pregunta_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-votos', 'orden', 'pregunta'], 'verbose_name': 'Pregunta frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
        migrations.AddField(
            model_name='faq',
            name='votos',
            field=models.PositiveIntegerField(default=0, help_text='Número de votos de utilidad'),
        ),
    ]
