# Generated by Django 5.1.7 on 2025-04-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0011_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='abierto', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('url_relacionada', models.CharField(blank=True, max_length=255)),
                ('captura_pantalla', models.ImageField(blank=True, null=True, upload_to='capturas_problemas/')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_reportados', to=settings.AUTH_USER_MODEL)),
                ('tipo_problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muebles.tipoproblema')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='muebles.reporteproblema')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_solucion', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='muebles.reporteproblema')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
