# Generated by Django 5.1.7 on 2025-04-01 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0012_alter_faq_options_faq_votos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['categoria', 'orden'], 'verbose_name': 'Pregunta frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
        migrations.AddField(
            model_name='faq',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faq',
            name='categoria',
            field=models.CharField(choices=[('CUENTA', 'Cuenta de usuario'), ('PAGOS', 'Pagos y facturación'), ('ENTREGAS', 'Entregas y logística'), ('MUEBLES', 'Productos y muebles'), ('SISTEMA', 'Sistema y mantenimiento'), ('OTROS', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='votos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
