# Generated by Django 5.1.7 on 2025-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0012_tipoproblema_reporteproblema_registrocambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='comision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='ganancia_propietario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mueble',
            name='comision',
            field=models.IntegerField(default=10, verbose_name='Comisión de propietario  (%)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comision_total',
            field=models.IntegerField(default=0),
        ),
    ]
