# Generated by Django 5.1.7 on 2025-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0013_alter_faq_options_faq_activo_faq_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(max_length=500),
        ),
    ]
