# Generated by Django 5.1.7 on 2025-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0014_alter_pregunta_pregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
