# Generated by Django 5.1.7 on 2025-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0014_carrito_session_key_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='dias',
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
