# Generated by Django 5.1.7 on 2025-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0015_remove_itemcarrito_dias_carrito_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='dias',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
