# Generated by Django 5.1.7 on 2025-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0016_alter_faq_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
