# Generated by Django 5.1.7 on 2025-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0016_itemcarrito_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='servicio_instalacion',
            field=models.BooleanField(default=False),
        ),
    ]
