# Generated by Django 5.1.7 on 2025-04-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muebles', '0017_alter_faq_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['categoria', '-votos'], 'verbose_name': 'Pregunta frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='orden',
        ),
    ]
